import com.example.mstats.R

object PlayerRepository {
    val players: List<PlayerModel> = listOf(
        PlayerModel(
            overall = "91",
            name = "Kylian Mbappé",
            number = "#9",
            position = "ST, LW",
            flagResId = R.drawable.flg_france,
            imageResId = R.drawable.p_mbappe,
            foot = "Right",
            age = "25",
            height = "182cm",
            weight = "75kg",
            contract = "2029",
            description = "Kylian Mbappé is a French professional soccer player who is recognized as one of the best talents in the modern generation of football. Born on December 20, 1998, Mbappé began his career at AS Monaco before joining Paris Saint-Germain (PSG) in 2017 for a record transfer. Known for his speed, dribbling skills, and exceptional goal-scoring ability, Mbappé has been a key player for both club and the French national team, including in France\"'\"s triumph at the 2018 World Cup. At a young age, he has won numerous awards and continues to be an icon of world football."
        ),
        PlayerModel(
            overall = "90",
            name = "Vinícius Júnior",
            number = "#7",
            position = "LW, LM",
            flagResId = R.drawable.flg_brazil,
            imageResId = R.drawable.p_vini,
            foot = "Right",
            age = "24",
            height = "176cm",
            weight = "73kg",
            contract = "2027",
            description = "Vinícius Júnior is a Brazilian professional soccer player who is widely regarded as one of the brightest stars in modern football. Born on July 12, 2000, Vinícius started his professional career at Flamengo before making a high-profile move to Real Madrid in 2018. Known for his explosive speed, agility, and flair on the ball, Vinícius has quickly become a key player for both Real Madrid and the Brazilian national team. His incredible dribbling ability and knack for scoring crucial goals have earned him a reputation as one of the most exciting young talents in world football. Vinícius continues to rise, achieving success at both the club and international levels."
        ),
        PlayerModel(
            overall = "90",
            name = "Jude Bellingham",
            number = "#5",
            position = "CAM, CM",
            flagResId = R.drawable.flg_eng,
            imageResId = R.drawable.p_judge,
            foot = "Right",
            age = "21",
            height = "186cm",
            weight = "75kg",
            contract = "2029",
            description = "Jude Bellingham is an English professional soccer player, celebrated as one of the brightest young talents in football. Born on June 29, 2003, in Stourbridge, England, he began his career at Birmingham City before joining Borussia Dortmund in 2020. Known for his skill, vision, and versatility as a midfielder, Bellingham has become a key player for both club and the England national team, making his senior debut in 2020. With a promising future, he is set to be a defining player of his generation."

        ),
        PlayerModel(
            overall = "86",
            name = "Rodrygo",
            number = "#11",
            position = "RW, CF",
            flagResId = R.drawable.flg_brazil,
            imageResId = R.drawable.p_rodrygo,
            foot = "Right",
            age = "23",
            height = "174cm",
            weight = "64kg",
            contract = "2028",
            description = "Rodrygo is a Brazilian professional soccer player known for his electrifying speed and technical skills. Born on January 9, 2001, in Osasco, Brazil, he began his career at Santos FC before joining Real Madrid in 2019. Rodrygo quickly made an impact at the club, showcasing his ability as a winger and scoring crucial goals in important matches. He has also represented the Brazilian national team, earning praise for his performances in international competitions. With a bright future ahead, Rodrygo is considered one of the most exciting young talents in world football."
        ),
        PlayerModel(
            overall = "86",
            name = "Luka Modrić",
            number = "#10",
            position = "CM, CAM",
            flagResId = R.drawable.flg_croatia,
            imageResId = R.drawable.p_modric,
            foot = "Right",
            age = "39",
            height = "172cm",
            weight = "66kg",
            contract = "2025",
            description = "Luka Modrić is a Croatian professional soccer player, widely regarded as one of the best midfielders of his generation. Born on September 9, 1985, in Zadar, Croatia, he began his career at Dinamo Zagreb before moving to Tottenham Hotspur in 2008. Modrić joined Real Madrid in 2012, where he has achieved tremendous success, including multiple UEFA Champions League titles and the FIFA Club World Cup. His exceptional passing, vision, and tactical intelligence were pivotal in leading Croatia to the 2018 World Cup final, where he was awarded the Golden Ball for being the \"tournament's\" best player."
        ),
        PlayerModel(
            overall = "86",
            name = "Dani Carvajal",
            number = "#2",
            position = "RB",
            flagResId = R.drawable.flg_spain,
            imageResId = R.drawable.p_carjaval,
            foot = "Right",
            age = "32",
            height = "173cm",
            weight = "73kg",
            contract = "2025",
            description = "Dani Carvajal is a Spanish professional soccer player known for his remarkable defensive skills and attacking contributions as a right-back. Born on January 11, 1992, in Leganés, Spain, he began his career in Real \"Madrid's\" youth academy before a successful loan at Bayer Leverkusen. Carvajal returned to Real Madrid in 2013, where he has become an integral part of the team, winning numerous titles including the UEFA Champions League. His pace, stamina, and ability to provide assists make him a vital player in both defense and attack, and he has also represented Spain at the international level."
        ),
        PlayerModel(
            overall = "89",
            name = "Thibaut Courtois",
            number = "#1",
            position = "GK",
            flagResId = R.drawable.flg_belgium,
            imageResId = R.drawable.p_curtoa,
            foot = "Left",
            age = "32",
            height = "200cm",
            weight = "96kg",
            contract = "2026",
            description = "Thibaut Courtois is a Belgian professional soccer player who is widely regarded as one of the top goalkeepers in the world. Born on May 11, 1992, in Bree, Belgium, he began his career at Genk before moving to Atlético Madrid, where he gained recognition for his outstanding performances. After a successful stint at Chelsea, Courtois joined Real Madrid in 2018. Known for his exceptional shot-stopping ability, composure under pressure, and impressive height, he has played a crucial role in Real \"Madrid's\" success and is a key figure for the Belgian national team."
        ),
        PlayerModel(
            overall = "88",
            name = "Federico Valverde",
            number = "#8",
            position = "CM, RM",
            flagResId = R.drawable.flg_urugay,
            imageResId = R.drawable.p_valvelde,
            foot = "Right",
            age = "26",
            height = "182cm",
            weight = "78kg",
            contract = "2026",
            description = "Federico Valverde is an Uruguayan professional soccer player celebrated for his versatility and tireless work rate in midfield. Born on July 22, 1998, in Montevideo, Uruguay, he joined Real Madrid in 2016 after a standout spell at Peñarol. Valverde quickly became a key player for Real Madrid, showcasing his ability to contribute both defensively and offensively. His remarkable stamina, technical skills, and tactical awareness have made him instrumental in the \"club's\" achievements, including their Champions League titles, and he has also represented Uruguay at various international levels."
        ),
        PlayerModel(
            overall = "88",
            name = "Antonio Rüdiger",
            number = "#22",
            position = "CB",
            flagResId = R.drawable.flg_germany,
            imageResId = R.drawable.p_rudiger,
            foot = "Right",
            age = "31",
            height = "190cm",
            weight = "86kg",
            contract = "2029",
            description = "Antonio Rüdiger is a German professional soccer player known for his physical presence, strength, and defensive capabilities. Born on March 3, 1993, in Berlin, Germany, he began his career at Stuttgart before moving to England to play for Chelsea, where he won multiple trophies, including the Champions League. In 2022, Rüdiger joined Real Madrid, where he has continued to showcase his leadership qualities and solid defensive performances. He is also a prominent figure for the German national team, participating in various international tournaments."
        ),
        PlayerModel(
            overall = "85",
            name = "David Alaba",
            number = "#4",
            position = "CB, LB",
            flagResId = R.drawable.flg_austria,
            imageResId = R.drawable.p_david,
            foot = "Left",
            age = "32",
            height = "180cm",
            weight = "78kg",
            contract = "2026",
            description = "David Alaba is an Austrian professional soccer player recognized for his versatility, capable of playing as a defender or midfielder. Born on June 24, 1992, in Vienna, Austria, he spent the majority of his career at Bayern Munich, where he won numerous titles, including the Champions League and Bundesliga. In 2021, Alaba signed with Real Madrid, bringing his extensive experience and skill to the team. Known for his tactical intelligence and ability to contribute to both defense and attack, he has been a crucial player in Real Madrid's recent successes."
        ),
        PlayerModel(
            overall = "85",
            name = "Éder Militão",
            number = "#3",
            position = "CB",
            flagResId = R.drawable.flg_brazil,
            imageResId = R.drawable.p_militao,
            foot = "Right",
            age = "26",
            height = "186cm",
            weight = "78kg",
            contract = "2026",
            description = "Éder Militão is a Brazilian professional soccer player known for his defensive prowess and aerial ability. Born on January 18, 1998, in Sertãozinho, Brazil, he started his career at São Paulo before making a name for himself at Porto. In 2019, Militão joined Real Madrid, where he has become an integral part of the \"team's\" defense. His speed, strength, and ability to read the game make him a key player in critical matches. Militão has also represented Brazil at various youth levels and made his senior debut in 2019."
        ),
        PlayerModel(
            overall = "83",
            name = "Eduardo Camavinga",
            number = "#6",
            position = "ALL ROLE",
            flagResId = R.drawable.flg_france,
            imageResId = R.drawable.p_cama,
            foot = "Left",
            age = "21",
            height = "182cm",
            weight = "68kg",
            contract = "2029",
            description = "Eduardo Camavinga is a French professional soccer player regarded as one of the most promising young talents in football. Born on November 10, 2002, in Miconje, Angola, he began his career at Rennes, where he gained attention for his impressive skills and maturity at a young age. In 2021, Camavinga joined Real Madrid, quickly establishing himself as a key midfielder known for his dribbling, vision, and tactical awareness. He has already represented France at various youth levels and has made significant contributions to the senior team."
        ),
        PlayerModel(
            overall = "81",
            name = "Lucas Vázquez",
            number = "#17",
            position = "RB",
            flagResId = R.drawable.flg_spain,
            imageResId = R.drawable.p_vaz,
            foot = "Right",
            age = "33",
            height = "173cm",
            weight = "70kg",
            contract = "2025",
            description = "Lucas Vázquez is a Spanish professional soccer player known for his versatility and industrious work ethic on the right flank. Born on July 1, 1991, in Curtis, Spain, he came through the youth ranks at Real Madrid and has been an important squad player since rejoining the club in 2015. Vázquez is capable of playing as a winger or full-back, providing crucial assists and goals. His determination and commitment have made him a fan favorite and an essential part of the team's dynamics."
        )
    )
}
